// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDioR5dUl1TcLK_AX8o_AjzhpDNRxaZY2Y',
    appId: '1:198750305277:web:13335437ebff7010dbf794',
    messagingSenderId: '198750305277',
    projectId: 'quickquote-25',
    authDomain: 'quickquote-25.firebaseapp.com',
    storageBucket: 'quickquote-25.firebasestorage.app',
    measurementId: 'G-DC8E4TC22V',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAOH9uyo6GVmVEj1lULg-ZeY2Bw3H3CjiE',
    appId: '1:198750305277:android:5d9638d752411294dbf794',
    messagingSenderId: '198750305277',
    projectId: 'quickquote-25',
    storageBucket: 'quickquote-25.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDUF-onVGEGir-Q-bM-20vvMIuznS5yT4c',
    appId: '1:198750305277:ios:e12af3870c97bba8dbf794',
    messagingSenderId: '198750305277',
    projectId: 'quickquote-25',
    storageBucket: 'quickquote-25.firebasestorage.app',
    iosBundleId: 'com.example.qouteApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDUF-onVGEGir-Q-bM-20vvMIuznS5yT4c',
    appId: '1:198750305277:ios:e12af3870c97bba8dbf794',
    messagingSenderId: '198750305277',
    projectId: 'quickquote-25',
    storageBucket: 'quickquote-25.firebasestorage.app',
    iosBundleId: 'com.example.qouteApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDioR5dUl1TcLK_AX8o_AjzhpDNRxaZY2Y',
    appId: '1:198750305277:web:a079abe9216f7277dbf794',
    messagingSenderId: '198750305277',
    projectId: 'quickquote-25',
    authDomain: 'quickquote-25.firebaseapp.com',
    storageBucket: 'quickquote-25.firebasestorage.app',
    measurementId: 'G-PCWBR3KYYD',
  );
}
